version: '3'

services:
  crdb:
    image: cockroachdb/cockroach:v19.1.4
    command: start --insecure
    volumes:
        - "/tmp/roleypoly-data/crdb:/cockroach/cockroach-data"
    ports:
        - "8081:8080"
        - "26257:26257"