name: Deploy

on: 
  repository_dispatch:
    types: [deploy]

jobs:
  change_version:
    name: Change Version
    runs-on: ubuntu-latest
    env:
      TARGET_FILE: ./terraform/app/tags.auto.tfvars.json
      TARGET_ENV: ${{ github.event.client_payload.environment }}
      TARGET_APP: ${{ github.event.client_payload.app }}
      TARGET_TAG: ${{ github.event.client_payload.new_tag }}
      TARGET_DESCRIPTION: ${{ github.event.client_payload.description }}
        
    steps:
      - uses: actions/checkout@master

      - name: Change terraform/app/tags.auto.tfvars.json -- ${{ github.event.client_payload.app }} on ${{ github.event.client_payload.environment }} to ${{ github.event.client_payload.new_tag }}
        run: |
          mv "${TARGET_FILE}" "${TARGET_FILE}~"
          cat "${TARGET_FILE}~" | jq ".deployment_env.${TARGET_ENV}.${TARGET_APP} |= \"${TARGET_TAG}\"" | tee $TARGET_FILE
          rm "${TARGET_FILE}~"
          cat "${TARGET_FILE}" | grep -E ${TARGET_TAG}

      - name: Setup Git
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
        
        - name: Push changes
        run: |
          git config --local user.email "gh-automation@roleypoly.com"
          git config --local user.name "Roleypoly GitOps Automation"
          git add ${TARGET_FILE}
          git commit -m "gitops(deploy): updated ${TARGET_APP} in ${TARGET_ENV} to ${TARGET_TAG}\n\n${TARGET_DESCRIPTION}"
          git push